### ISSUE TITLE
2-12 (哈希表) 作业答案征集令

### ISSUE THREAD

**Issue by hengxin** [hengxin/problem-solving-class-problems#12]
- [ ] 哈希表均匀采样 (TC 11.2-6) [10]
  - 采样算法
  - 复杂度分析
  - 正确性证明

**Comment by hengxin** [comment]
@FitzLeopard 我明天看后给你反馈。

**Comment by FitzLeopard** [comment]
Revision has been made.

**Comment by FitzLeopard** [comment]
Revision has been made.
[HashSampling.pdf](https://github.com/hengxin/problem-solving-class-problems/files/2180832/HashSampling.pdf)

**Comment by hengxin** [comment]
@FitzLeopard 收到，谢谢。
