### ISSUE TITLE
问题求解第二学期习题答案征集——作业订正替代方案

### ISSUE THREAD

**Issue by hengxin** [hengxin/problem-solving-class-problems#14]
# 说明:
- [0.5] 表示该题可用来顶替一半需要订正的题目
- [1]    表示该题可用来顶替所有需要订正的题目
- 如果超额高质量完成，[0.5] 可提升为 [1]
- 在下面留言领取题目
- 本替代方案截止日期可适当放宽（但需有基本的进度保证）
- **累计领取题目数/人数统计：6/6**

# 要求:
- 中英文都可以
- 逻辑清晰。鼓励自主思考、鼓励自行扩展题目。
- 参考: [2-1-correctness.pdf](https://github.com/hengxin/problem-solving-class-problems/blob/master/2017/2017-2nd/2-1-correctness/2-1-correctness.pdf) 

# 2-2 (算法的效率) 
- [ ] 凸多边形直径问题 [0.5]
  - 算法 + 正确性证明
  - 参考: 习题课课件
- [x] 平面上最近点对问题 [1]
  - 算法 + 正确性证明
  - 参考: CLRS 33.4
  - By 殷兆恒

# 2-3 (计数) 
- [x] 计算 \binom{n}{k} (CS 1.5-14) [0.5]
  - 算法 + 复杂度分析
  - 参考: 习题课课件
  - By 周涛

# 2-4 (分治法与递归) 
- [x] 最大和/积子数组问题 (TC 4.1-5) [1]
  - 分析不同效率的多种算法 (原理介绍 + 伪代码)
  - 最大积子数组问题作为扩展，只需要给出线性的算法
  - 参考: 习题课课件; 《编程珠玑》Column 8
  - By 韩博
- [ ] 电路布线问题 [0.5]
  - 算法 + 复杂度分析
  - 参考: 习题课课件

# 2-5 (递归) 
- [ ] The Art Gallery Problem [1]
  - 问题描述、定理证明、下界证明
  - 参考: 习题课课件; 《Proofs from THE Book》"How to Guard a Museum?"
- [ ] 递归式求解方法总结 [1]
  - first order linear recurrences
  - linear recurrences with constant coefficients
  - first order linear non-homogeneous recurrences
  - More
  - 参考: 习题课课件; 《An Introduction to the Analysis of Algorithms》 Chapters 2 and 3

# 2-7 (离散概率) 
- [ ] The Monty-Hall Problem [1]
  - 分析多种版本
  - 参考: 习题课课件; wiki 词条 "Monty Hall problem"
- [ ] The Boy/Girl Puzzle (CS 5.3-12) [0.5]
  - 两种方式解读 “one of the children is a girl”
  - 参考: 习题课课件; wiki 词条 "Boy or Girl paradox"

# 2-8 (概率分析)
- [ ] Coin Pattern Problem [1]
  - 两种计算方法
  - 如果能将找到这两种方法的联系则更好
  - 参考: 习题课课件; 《Concrete Mathematics》Sections 8.3 and 8.4

# 2-9 (排序与选择) 
- [ ] “01” Pattern Problem [0.5]
  - 奇数情况下的算法设计与正确性证明
  - 偶数情况下的对手论证与证明
  - 参考: 习题课课件; Jeff 讲义 (见课程网站)

# 2-10 (基本数据结构)
- [x] Stack <-> Queue [1]
  - 两个 stacks 实现一个 queue
    - 参考:  习题课课件
  - 两个 queues 实现一个 stack
    - 参考: [here](https://cstheory.stackexchange.com/a/2589/12739) and [here](https://cstheory.stackexchange.com/a/5655/12739)
 - By 杜星亮 

# 2-11 (堆排序) 
- [ ] Heapsort worst-case Omega(n log n) (TC 6.4-4) [0.5]
  - 如何构造最坏的例子
  - 参考: 习题课课件
- [ ] Heapsort best-case Omega(n log n) (TC 6.4-5) [1]
  - 证明
  - 参考: 习题课课件; TAOCP Vol. 3 Solution to Ex 32 of Section 5.2.3
- [ ] Counting # of heaps of size n [0.5]
  - 参考: 习题课课件; Paper "The Analysis of Heapsort", 见课程网站

# 2-12 (哈希表) 
- [x] 哈希表均匀采样 (TC 11.2-6) [1]
  - 采样算法
  - 复杂度分析
  - 正确性证明
  - By 肖江

# 2-14 (B 树)
- [x] B树节点个数 (TC 18.2-4) [1]
  - 问题分析与解答
  - By 董杨静

# 其它
- 本学期所学内容（包括阅读材料、课堂教学、习题课、Open Topics、OJ 题目）中你所感兴趣的某个话题

**Comment by 812719483** [comment]
2.2 平面上最近点对问题。 by 殷兆恒

**Comment by FitzLeopard** [comment]
Hashing
- by Rivers

**Comment by massimodong** [comment]
领取2-14(B树) TC 18.2-4

**Comment by GodCallMeGod** [comment]
2-4 最大和/积子数组问题

-- 韩博

**Comment by truthlistener** [comment]
领取2-3 (计数)
——周涛
