### ISSUE TITLE
问题求解第三学期作业订正替代方案

### ISSUE THREAD

**Issue by hengxin** [hengxin/problem-solving-class-problems#16]
## 说明:
- 任选一道题目即可
- 在下面留言领取题目（多人可选同一题目）
- 截止日期: 2019年01月20日 晚上 20:00 
(依成绩统计进度，截止日期可能会有延后; 但这不是你犯拖延症的理由。)
- 提交方式: 与作业订正提交方式相同。此外，也可**同时**向该 Git 项目提交 pull request。

## 1. 平摊分析
  - 问题: "自组织列表"平摊分析
  - 参考资料: [MIT OCW on Self-organizing Lists](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-046j-introduction-to-algorithms-sma-5503-fall-2005/video-lectures/lecture-14-competitive-analysis-self-organizing-lists/)
  - 要求:  观看教学视频，作笔记。描述问题、给出严格的证明过程

### 2.1 Updating MST
- 问题: 已知图 G 的最小生成树 T。当出现如下情况时，如何高效地得到 G 的新的最小生成树。
  - T 中某条边权值增加
  - T 中某条边权值减少
  - G 中某条边 (不在 T 中) 权值增加
  - G 中某条边 (不在 T 中) 权值减少
- 要求: 给出严格的证明。
- 提醒: 对某一两个小题, 给出严格的证明**可能**并非想象中那么简单。

### 2.2 Critical Edges
- 问题: An MST edge whose deletion from the graph would cause the MST weight to increase is called a critical edge. Show how to find all critical edges in a graph in time proportional to E log E.
- 参考资料: [Find all critical edges for minimum spanning tree @ cs-stackexchange](https://cs.stackexchange.com/q/93204/4911)
- 要求: 自行给出算法并给出严格证明; 或者检查参考资料中的算法与证明是否成立。
(两种方案均需提交报告。)

## 3. 带负权边的无向图上的最短路径问题
- 问题: 利用 Perfect Matching 求无向图(允许有负权边，但不允许有负圈)中的最短简单路径
- 参考资料: [Shortest Path Algorithms (math.sfu.ca, Math 408, Luis Goddyn).pdf](http://cslabcms.nju.edu.cn/problem_solving/images/4/42/Shortest_Path_Algorithms_%28math.sfu.ca%2C_Math_408%2C_Luis_Goddyn%29.pdf)
- 要求: 给出严格而详细的证明。
- 提醒: 参考材料中有少量笔误和大量未加证明的陈述。

## 4. 匹配
- 问题: 稳定婚姻问题
- 参考资料: Youtube 视频: [Stable Marriage Problem, Part 1](https://www.youtube.com/watch?v=Qcv1IqHWAzg)、[Stable Marriage Problem: Part 2](https://www.youtube.com/watch?v=LtTV6rIxhdo)
- 要求: 观看视频，作笔记。描述问题、算法以及证明。（可选: 问题的历史与发展）

## 5. 网络流
- 问题: 七个等价定理
- 参考资料: [Equivalence of Seven Major Theorems in Combinatorics (Robert Borgersen, 2004).pdf](http://cslabcms.nju.edu.cn/problem_solving/images/1/16/Equivalence_of_Seven_Major_Theorems_in_Combinatorics_%28Robert_Borgersen%2C_2004%29.pdf)
- 要求: 任选其中三个定理，证明它们的相互等价性，要给出严格而详细的证明过程。

**Comment by congee524** [comment]
B.K. Huang 171240513, wanna prepare for Question 5.

**Comment by massimodong** [comment]
选择题目2.2

**Comment by FancyPei** [comment]
Problem 3.

**Comment by Zhaoheng-Yin** [comment]
Problem 4 Zhao H. Yin

**Comment by zxy8888** [comment]
problem 4 
161120181赵新榆
